# Generated by Django 4.2.4 on 2023-08-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_image',
        ),
    ]
