# Generated by Django 4.2.4 on 2023-08-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_review_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
