# Generated by Django 4.2.4 on 2023-08-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_review_rating_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
