# Generated by Django 4.2.4 on 2023-09-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_remove_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
