# Generated by Django 4.2.4 on 2023-09-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_remove_review_movie_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
